### ISSUE TITLE
ERROR in bundle.js from UglifyJs

### ISSUE THREAD

**Issue by enrtama** [gianu/react-fittext#15]
I get this error when compiling:

SyntaxError: Unexpected token: operator (>) [./~/react-fittext/lib/ReactFitText.js:51,0]

**Comment by gianu** [comment]
I will take a look at it today.

**Comment by ericfong** [comment]
I got similar error.

I think safari cannot understand "=>" syntax

**Comment by enrtama** [comment]
This code would fix it in "react-fittext/lib/ReactFitText.js" replacing the function:

    _renderChildren: function () {
        return React.Children.map(this.props.children, function (child) {
            return React.cloneElement(child, {
                ref: function ref(c) {
                    return _this._childRef = c;
                }
            });
        });
    },

**Comment by Paveltarno** [comment]
@enrtama Thanks!
Only thing missing is to add
`var _this = this;`
at the beginning of the function

**Comment by ncherro** [comment]
Looks like this has been fixed in the master branch, but npm hasn't been updated (?).

If my package.json contains this line `"react-fittext": "https://github.com/gianu/react-fittext"` everything works, but if it contains `"react-fittext": "0.0.7"` (which happens when I `npm install --save react-fittext`) then I get the build error.

**Comment by enrtama** [comment]
@gianu Do you know when NPM is gonna be updated, I still have problems when running "npm install" of my dependencies from scratch.

I appreciate it.

**Comment by jDeppen** [comment]
Thanks, @ncherro, the github URL works!

**Comment by mmdonaldson** [comment]
Is there a reason why it hasn't been updated from npm?

**Comment by sroutledge** [comment]
I'm having this exact same issue, npm using the 0.0.7 version :(

**Comment by enrtama** [comment]
What I've done is adding the next line to my package.json dependencies:

`"react-fittext": "https://github.com/gianu/react-fittext",
`

**Comment by sroutledge** [comment]
Thanks, @enrtama, that's what we'll do for now. Would be nice to have the npm version updated though!

**Comment by Hydeo** [comment]
+1
Thanks for the workaround @enrtama

**Comment by denis-sokolov** [comment]
Version 1.0.0 released, the workarounds should not be necessary anymore.
